DROP TABLE BENEFICIARIOS;

CREATE TABLE [dbo].[BENEFICIARIOS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CPF] [varchar](14) NOT NULL,
	[NOME] [varchar](50) NOT NULL,
	[IDCLIENTE] [bigint] NOT NULL,
	PRIMARY KEY(ID),
	CONSTRAINT FK_Beneficiarios_Cliente FOREIGN KEY (IDCLIENTE)
    REFERENCES CLIENTES(ID)
);


